Intentionally fail

diff --git a/.github/workflows/main-merge-queue.yml b/.github/workflows/main-merge-queue.yml
--- a/.github/workflows/main-merge-queue.yml
+++ b/.github/workflows/main-merge-queue.yml
@@ -14,6 +14,8 @@ jobs:
         shell: bash
         run: |
           sleep 60
+          echo "testing error" >&2
+          exit 1
   test:
     runs-on: "ubuntu-latest"
     steps:
